"use client";

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/global.css';
import { NextUIProvider } from "@nextui-org/react";
import { Providers } from '@redux/provider';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'DM - Design Me',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="/favicon.ico" sizes="any" />

      </head>
      <body className={inter.className} style={{ position: 'relative' }}>
        <Providers>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </Providers>
      </body>
    </html>
  )
}
