import type { Metadata } from 'next'
import Layout from './_components/layout'

export const metadata: Metadata = {
    description: 'Generated by create next app',
}

export default function DashboardLayout({ children }: { children: React.ReactNode }) {

    return (
        <Layout>
            {children}
        </Layout>
    )
}
