import type { Metadata } from 'next'
import Layout from './_components/layout'
import AuthGuard from './_components/guard/AuthGuard'

export const metadata: Metadata = {
    description: 'Generated by create next app',
}

export default function DashboardLayout({ children }: { children: React.ReactNode }) {

    return (
        <AuthGuard>
            <Layout>
                {children}
            </Layout>
        </AuthGuard>
    )
}
