import { Topic, TopicStatus } from "@/services/topic/types";

export const topics: Topic[] = [
    {
        id: '1',
        title: 'Docker',
        description: 'Tìm hiểu về Docker',
        createdAt: '',
        updatedAt: '',
        deletedAt: null,
        parent: '',
        tags: ['Developer', 'Fullstack', 'Backend', 'Docker'],
        slug: '',
        status: TopicStatus.IN_PROGESS,
    },
    {
        id: '2',
        title: 'Docker',
        description: 'Tìm hiểu về Docker',
        createdAt: '',
        updatedAt: '',
        deletedAt: null,
        parent: '',
        tags: ['Developer', 'Fullstack', 'Backend', 'Docker'],
        slug: '',
        status: TopicStatus.IN_PROGESS,
    },
    {
        id: '3',
        title: 'Docker',
        description: 'Tìm hiểu về Docker',
        createdAt: '',
        updatedAt: '',
        deletedAt: null,
        parent: '',
        tags: ['Developer', 'Fullstack', 'Backend', 'Docker'],
        slug: '',
        status: TopicStatus.IN_PROGESS,
    },
    {
        id: '4',
        title: 'Docker',
        description: 'Tìm hiểu về Docker',
        createdAt: '',
        updatedAt: '',
        deletedAt: null,
        parent: '',
        tags: ['Developer', 'Fullstack', 'Backend', 'Docker'],
        slug: '',
        status: TopicStatus.TODO,
    },
    {
        id: '5',
        title: 'Next Js',
        description: 'Tìm hiểu về Framework NextJs',
        createdAt: '',
        updatedAt: '',
        deletedAt: null,
        parent: '',
        tags: ['Developer', 'Fullstack', 'Backend', 'Docker'],
        slug: '',
        status: TopicStatus.COMPLETED,
    },
]